name: Bug Report
description: Report a bug with estimated effort to fix
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report Template
        Please provide detailed information about the bug you encountered.
        
  - type: input
    id: bug-title
    attributes:
      label: Bug Title
      description: Brief, descriptive title for this bug
      placeholder: "Brief description of the issue"
    validations:
      required: true
      
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: |
        ### What happened?
        [Describe the bug clearly]
        
        ### What did you expect to happen?
        [Describe the expected behavior]
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: dropdown
    id: story-points
    attributes:
      label: Story Points (Effort to Fix)
      description: Estimated effort to fix this bug (Fibonacci sequence)
      options:
        - "1 - Very Small"
        - "2 - Small" 
        - "3 - Medium Small"
        - "5 - Medium"
        - "8 - Large"
        - "13 - Very Large"
        - "21 - Extra Large"
        - "? - Needs Investigation"
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - "Critical - System is unusable"
        - "High - Major feature broken"
        - "Medium - Minor feature affected"
        - "Low - Cosmetic issue"
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgently should this be fixed?
      options:
        - "Critical"
        - "High"
        - "Medium"
        - "Low"
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        ### Environment:
        - OS: [e.g. macOS, Windows, Linux]
        - Browser: [e.g. Chrome, Firefox, Safari]
        - Version: [e.g. 1.0.0]
        - Java Version: [e.g. 17]
        - Additional context: [any other relevant information]
      
  - type: textarea
    id: logs-screenshots
    attributes:
      label: Logs and Screenshots
      description: Add any relevant logs, error messages, or screenshots
      placeholder: |
        ### Error Messages:
        ```
        [Paste any error messages here]
        ```
        
        ### Screenshots:
        [Attach screenshots if applicable]
        
        ### Logs:
        [Paste relevant log entries]
      
  - type: checkboxes
    id: affected-areas
    attributes:
      label: Affected Areas
      description: Which parts of the system are affected?
      options:
        - label: User Management
        - label: Authentication/Authorization
        - label: User Preferences
        - label: API Endpoints
        - label: Database
        - label: Frontend Integration
        - label: Documentation
        - label: DevOps/Deployment