name: build-and-push-docker
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build runner jar (Java 17) and place where Dockerfile expects it
        run: |
          mvn -B -DskipTests \
             -Dquarkus.package.type=uber-jar \
             -Dmaven.compiler.release=17 \
             -Dmaven.compiler.source=17 \
             -Dmaven.compiler.target=17 \
             package
          mkdir -p target/quarkus
          cp target/*-runner.jar target/quarkus/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (latest)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: thnndnly/shop-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max